services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local
    depends_on:
      - db
    volumes:
      - ./backend:/code
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:11
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/code
      - /code/node_modules
      - /code/.next
  reverse-proxy:
    depends_on:
      - frontend
      - backend
    image: caddy:2.0.0
    ports:
      - 3001:3001
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
version: '3.4'
